### ISSUE TITLE
http://archive.canonical.com/ load balancing mirror at 91.189.91.15 is just a blank apache fresh install

### ISSUE THREAD

**Issue by superkuh** [canonical-websites/www.canonical.com#261] opened 2018-04-10 13:33 UTC
## Summary

The http://archive.canonical.com/ load balancing mirror at http://91.189.91.15/ is just a blank apache fresh install. When the Ubuntu round robin or whatever load balancer tells Ubuntu OS client package managers to use this mirror they fail and abort.

This has been going on for 2 days now.

## Process

Well, since it's a load balancer/DNS issue it really is sort of random. But since my OS has cached that IP for archive.canonical.com all I have to do is an,

$ apt-get update
...
Hit http://old-releases.ubuntu.com lucid-security/universe Packages
Hit http://old-releases.ubuntu.com lucid-security/multiverse Packages
Hit http://old-releases.ubuntu.com lucid-backports/main Packages
Hit http://old-releases.ubuntu.com lucid-backports/restricted Packages
Hit http://old-releases.ubuntu.com lucid-backports/universe Packages
Hit http://old-releases.ubuntu.com lucid-backports/multiverse Packages
...
Err http://archive.canonical.com lucid/partner Packages
404 Not Found [IP: 91.189.91.15 80]
Err http://archive.canonical.com lucid/partner Packages
404 Not Found [IP: 91.189.91.15 80]
...
W: Failed to fetch http://archive.canonical.com/ubuntu/dists/lucid/partner/binary-amd64/Packages.gz 404 Not Found [IP: 91.189.91.15 80]

W: Failed to fetch http://archive.canonical.com/dists/lucid/partner/binary-amd64/Packages.gz 404 Not Found [IP: 91.189.91.15 80]

E: Some index files failed to download, they have been ignored, or old ones used instead.

## Current and expected result

I expect the http://archive.canonical.com/ mirror to not just be a blank fresh apache install and actually have a repo and packages on it. This one currently does not.

I can access other servers that http://archive.canonical.com/ resolves to by tunneling my brower's DNS out to a remote server (ssh socks 5 proxy to VPS) and see that they work. But since my OS has cached this bad one it will not be fixed until I restart. I don't restart more than once a month usually.

**Comment by nottrobin** [comment] 2018-04-26 14:57
This appears to be a duplicate of https://github.com/canonical-websites/www.ubuntu.com/issues/2916. Closing.

**Closed by nottrobin** 2018-04-26 14:57 UTC
