### ISSUE TITLE
Career page feed broken

### ISSUE THREAD

**Issue by apathyuk** [canonical-websites/www.canonical.com#308] opened 2018-10-09 11:27 UTC
## Summary

Canonical career feed fails to load

## Process

The error shows when viewing the career page

**Comment by anthonydillon** [comment] 2018-10-09 12:11
@apathyuk thank you very much for taking the time to report this issue. We are aware and are working on resolving the issue.

Duplicate of https://github.com/canonical-websites/www.canonical.com/issues/306

**Closed** 2018-10-09 12:16 UTC
